learning_log/urls.py
"""learning_log URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
'''
Author: Mr. Zhangyi
Date: 2022-03-09 09:55:00
FilePath: /learning_log/learning_logs/urls.py
Description: 定义learning_logs的URL模式。
Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
version: v0.1
'''
from django.urls import path
from . import views
app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry,
         name='new_entry'),
]

learning_logs/models.py
'''
Author: Mr. Zhangyi
Date: 2022-03-08 16:45:33
FilePath: /learning_log/learning_logs/models.py
Description: 
Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
version: v0.1
'''
from django.db import models

# Create your models here.
class Topic(models.Model):
    """用户学习的主题。"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示。"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识。"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'
        def __str__(self):
            """返回模型的字符串表示。"""
            return f"{self.text[:50]}..."

learning_logs/forms.py
'''
Author: Mr. Zhangyi
Date: 2022-03-09 16:13:57
FilePath: /learning_log/learning_logs/forms.py
Description: 
Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
version: v0.1
'''
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ' '}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
'''
Author: Mr. Zhangyi
Date: 2022-03-08 16:45:33
FilePath: /learning_log/learning_logs/views.py
Description: 
Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
version: v0.1
'''
from django.shortcuts import render, redirect
from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """学习笔记的主页。"""
    return render(request, 'index.html')


def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)


def topic(request, topic_id):
    """显示单个主题及其所有的条目。"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', context)


def new_topic(request):
    if request.method != 'POST':
        # 未提交数据：创建一个新表单。
        form = TopicForm()
    else:    # POST提交的数据：对数据进行处理。
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    # 显示空表单或指出表单数据无效。
    context = {'form': form}
    return render(request, 'new_topic.html', context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)

learning_logs/templates/base.html
<!--
 * @Author: Mr. Zhangyi
 * @Date: 2022-03-09 10:23:48
 * @FilePath: /learning_log/learning_logs/templates/base.html
 * @Description: 
 * Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
 * @version: v0.1
-->
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}

learning_logs/templates/index.html
<!--
 * @Author: Mr. Zhangyi
 * @Date: 2022-03-09 10:02:21
 * @FilePath: /learning_log/learning_logs/templates/index.html
 * @Description: 
 * Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
 * @version: v0.1
-->
{% extends "base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic
you're
learning about.</p>
{% endblock content %}

learning_logs/templates/new_entry.html
{% extends "base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}
    </a></p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Add entry</button>
</form>
{% endblock content %}

learning_logs/templates/new_topic.html
<!--
 * @Author: Mr. Zhangyi
 * @Date: 2022-03-10 15:44:14
 * @FilePath: /learning_log/learning_logs/templates/new_topic.html
 * @Description: 
 * Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
 * @version: v0.1
-->
{% extends "base.html" %}
{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'learning_logs:new_topic' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Add topic</button>
</form>
{% endblock content %}

learning_logs/templates/topic.html
<!--
 * @Author: Mr. Zhangyi
 * @Date: 2022-03-09 16:06:23
 * @FilePath: /learning_log/learning_logs/templates/topic.html
 * @Description: 
 * Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
 * @version: v0.1
-->
{% extends 'base.html' %} {% block content %}
<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/topics.html
<!--
 * @Author: Mr. Zhangyi
 * @Date: 2022-03-09 10:30:31
 * @FilePath: /learning_log/learning_logs/templates/topics.html
 * @Description: 
 * Copyright (c) 2022 by Mr. Zhangyi/Chinatelecom, All Rights Reserved. 
 * @version: v0.1
-->
{% extends "base.html" %}
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    <br>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}